Initial commit
merokudao/namespace pull request #3
Opened 2023-03-20 06:59 UTC by harshit-bitpack

contracts' repo under hardhat manager added

2023-03-20 16:58 UTC, VanxhBitpack approved these changes

2023-03-20 16:58 UTC, VanxhBitpack commented on .gitignore
> +packages/contract/.env
Make it a symlink to workspace root `.env`
and make it not ignore packages/contract/.env by adding `!packages/contract/.env` to `.env`

2023-03-20 16:58 UTC, VanxhBitpack commented
Please do these changes

2023-03-22 06:23 UTC, r4881t requested changes

2023-03-22 06:23 UTC, r4881t commented on packages/contract/scripts/addDappNames.js
> +        await dappNameList.setDappNames(["dapp1", "dapp2", "dapp3"]);
Update this to read from a file.

2023-03-22 06:23 UTC, r4881t commented on packages/contract/scripts/config.json
> +{
Since this is updated after deployment, does it makes sense to have valid addresses here? Or are we good with a dummy address like 0x000

2023-03-22 06:23 UTC, r4881t commented on packages/contract/test-old/Lock.js
> +const {
Remove

2023-03-23 05:49 UTC, r4881t commented on packages/contract/contracts/DevNFTUpgradeable.sol
> +    function safeMintDevNFT(address to, string memory uri, string memory devName) public whenNotPaused {
Here, remove `to` param. It should mint to the sender of the message.

2023-03-24 05:26 UTC, r4881t approved these changes
lgtm

2023-03-28 06:40 UTC, 0xbitmonk commented on .gitignore
> +packages/contract/.env
git rm --cached folder_name
echo folder_name >> .gitignore

2023-03-29 15:43 UTC, merged